services:
  git:
    image: codeberg.org/forgejo/forgejo:10
    restart: unless-stopped      
    container_name: git
    environment: 
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=db:5432
      - FORGEJO__database__NAME=forgejo
      - FORGEJO__database__USER=forgejo
      - FORGEJO__database__PASSWD=forgejo
      - FORGEJO__DEFAULT__APP_NAME="Butter dog"
      - FORGEJO__DEFAULT__APP_SLOGAN="the dog with the butter"
      - FORGEJO__server__ROOT_URL=https://git.nuv.systems
      - FORGEJO__server__OFFLINE_MODE=false
      - FORGEJO__mirror__ENABLED=true
    networks:
      - proxy
      - forgejo
    volumes:
      - forgejo:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      caddy: git.nuv.systems
      caddy.reverse_proxy: "{{upstreams 3000}}"
      caddy.tls.dns: "ionos ${API_Key}"
      caddy.tls.resolvers: "1.1.1.1"
    depends_on: 
      - db

  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_USER=forgejo
      - POSTGRES_PASSWORD=forgejo
      - POSTGRES_DB=forgejo
    networks: 
      - forgejo
    volumes:
      - forgejo_postgres:/var/lib/postgresql/data

volumes: 
  forgejo:
  forgejo_postgres:

networks:
  proxy:
    external: true
  forgejo:
