services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - homarr:/appdata
    env_file: ".env"
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    ports:
      - '7575:7575'
    networks:
      - proxy
    labels:
      caddy: nuv.systems
      caddy.reverse_proxy: "{{upstreams 7575}}"
      caddy.tls.dns: "ionos ${API_Key}"
      caddy.tls.resolvers: "1.1.1.1"

volumes:
  homarr:

networks:
  proxy:
    external: true
