services:
  portainer:
    image: portainer/portainer-ee:lts
    container_name: portainer
    restart: always
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment: 
      PORTAINER_LICENSE_KEY: "3-7lpfETutr36iAFdbOc4+RKw5Ls2MnHI3A/SLj5bGiZu5qiVznF3lqBA4pht26PJNgjcF4eVftmBrtzU+Bl49wcU9P5DBw+BTA9JmT2osGmwofupwSceaVBaZumEr+pSt"
    networks:
      - caddy_caddy
    labels:
      caddy: portainer.nuv.systems
      caddy.reverse_proxy: "{{upstreams 9000}}"
      caddy.tls.dns: "ionos 2931814bd5d6472aaf3a73fa3c50c25c.ftPD9SB9oODeP2MjGaiMnpLSMPoomkjYWu7ZSygRilXBBrTrilm1G2mrtkyTfN5Xm5sDUEFt5bg-c0pArjIEbA"
      caddy.tls.resolvers: "1.1.1.1"

volumes:
  portainer_data:

networks:
  caddy_caddy:
    external: true
